services:
  odoo:
    image: odoo:16  
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo_data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo

  db:
    image: postgres:14  
    environment:  
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4  
    depends_on:
      - db
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=22521276@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=tester
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  odoo_data:
  db_data:
  pgadmin_data:
